### ISSUE TITLE
I can’t download any apps from the Google play

### ISSUE THREAD

**Issue by dingus-n** [AdguardTeam/AdGuardVPNForAndroid#380] opened 2023-11-08 01:53 UTC
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

v2.5.6 (29)

### Operating mode

VPN

### Environment

```markdown
- OS: Android 13
- Device: Samsung A51
- Firmware: OneUI 5.1
```

### Root access

- [X] Yes, I have it.

### Issue Details

Steps to reproduce Google play error:
1. Connect to Mexican server
2. Try to install any app
3. Wait
4. Check 'Screenshot 1'
----
Steps to reproduce YouTube error:
1. Connect to Mexican server
2. Open any video and turn on "stats for nerds"
3. Check 'Screenshot 2'

### Expected Behavior

Google services should have normal speed

### Screenshots

<details><summary>Screenshot speedtest:</summary>

![image](https://github.com/AdguardTeam/AdGuardVPNForAndroid/assets/74512154/4d198075-fcc7-465c-bfdf-4b056766ed3c)

</details>

<details><summary>Screenshot 1:</summary>

![photo_2023-11-07_19-46-12 (2)](https://github.com/AdguardTeam/AdGuardVPNForAndroid/assets/74512154/80c958f3-d86b-40a1-98ac-8f2747bbb6d0)

</details>

<details><summary>Screenshot 2:</summary>

![image](https://github.com/AdguardTeam/AdGuardVPNForAndroid/assets/74512154/b2fdf88a-5c86-4b0e-94f9-261f91572a7a)

</details>

### Additional Information

I cant download any apps from the google play when Im connected to a mexican server. Not long before this, apps were downloaded but terribly slow, now they are not downloading at all. There is no problem with other servers. I tried changing DNS and some settings, it didnt help. YouTube speed has also decreased. Speedtest.net shows speed 80-90mbps. But YouTube shows a maximum of 4000kbps (you can look at stats for nerds).

**Comment by maxikuzmin** [comment] 2023-11-21 11:52
@nikitaed most likely this problem is more widespread as it repeats on windows as well, but you could try removing downloads packages from "Excluded apps"
Go to Settings tab -> General -> Advanced -> Low-level settings -> Excluded apps -> remove "Disable Downloads Manager..."

**Comment by nikitaed** [comment] 2023-11-21 12:19
@maxikuzmin Yes, I did it, thank you. I also resolved the issue with YouTube by blocking QUIC ports (or disabling the QUIC flag in Chrome). When I set the QUIC flag to 'disabled,' the speed increases

**Comment by maxikuzmin** [comment] 2023-12-05 14:41
@dingus-n could you check to see if the download is broken in the browser? In theory, the fact that we removed the download manager should break, not fix. Browser and google play use downloads packages both

**Comment by dingus-n** [comment] 2023-12-05 15:13
@maxikuzmin The removal of "Disable Downloads Manager..." from Excluded apps did not solve the problem with Google Play. Applications are still not downloading. It didn't affect downloads from the browser

**Comment by dingus-n** [comment] 2023-12-10 19:53
@maxikuzmin Is there any progress on resolving this issue? When do you expect it to be resolved?

**Comment by maxikuzmin** [comment] 2023-12-11 13:53
@dingus-n we need some more time, please wait

**Comment by dingus-n** [comment] 2023-12-12 23:36
Also, Youtube is not working on my Android TV when I'm connected to the Mexican server. Everything is working normally with the rest of the servers

<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdGuardVPNForAndroid/assets/74512154/bd2a737c-9749-47fb-9155-ebf3820b1db6)


</details>

<details><summary>Screenshot 2:</summary>

![image](https://github.com/AdguardTeam/AdGuardVPNForAndroid/assets/74512154/b6c70988-d3b4-4cfb-8aa7-9c0631fa7523)


</details>

**Comment by maxikuzmin** [comment] 2023-12-18 18:05
@dingus-n we investigate the problem, please wait

**Comment by maxikuzmin** [comment] 2023-12-22 08:19
@dingus-n it would be nice to get your logs.

- Enable debug logging:

Settings -> General -> Advanced -> Logging level -> Debug

- Reproduce the issue related to the button behaviour, then remember the exact time when it happened

- Collect logs:

Settings -> General -> Advanced -> Export logs and system info

- Sent this file to [devteam@adguard.com](mailto:devteam@adguard.com):

mention the 380 number in the subject
specify the exact time when the issue occurred

**Comment by maxikuzmin** [comment] 2023-12-22 08:19
@dingus-n we recently changed addresses, maybe the problem is no longer there, please check it out

**Comment by dingus-n** [comment] 2023-12-22 08:38
@maxikuzmin 
> Settings -> General -> Advanced -> Logging level -> Debug

I dont have a "debug" option, only "Extended" or "Extreme". Which one should I choose?

**Comment by maxikuzmin** [comment] 2023-12-22 15:04
@dingus-n sorry, you need "Extended" logs

**Comment by maxikuzmin** [comment] 2023-12-26 20:02
@dingus-n any news?

**Comment by dingus-n** [comment] 2023-12-27 02:23
@maxikuzmin Everything is the same. The IP address of the Mexican server has not changed, and applications in the Google Play still are not downloading

**Comment by maxikuzmin** [comment] 2023-12-27 20:17
@dingus-n please send us the extended logs as I wrote above to email [devteam@adguard.com](mailto:devteam@adguard.com)

**Comment by dingus-n** [comment] 2023-12-27 20:37
@maxikuzmin I have already sent logs to the devs in Telegram twice. What is the point? It has been 2 months and I cannot see any concrete information in this thread. What is the problem and how soon will it be fixed?

**Comment by maxikuzmin** [comment] 2023-12-27 20:52
@dingus-n the problem is that you initially sent us usual logs. In order to understand, we need extended logs. That's why I ask you to send extended logs to our email. It will be problematic to find your logs in Telegram now. Please record the extended logs, then email them to [devteam@adguard.com](mailto:devteam@adguard.com) with the time of the problem and the Issue number (380)

**Comment by dingus-n** [comment] 2023-12-27 21:23
@maxikuzmin I've sent the logs. I hope you'll be able to find a solution soon. It seems a kinda stupid to me to ask for logs for a global problem that even your devs are having trouble with

**Comment by maxikuzmin** [comment] 2023-12-28 17:30
@dingus-n thanks for your logs :)

**Comment by maxikuzmin** [comment] 2024-01-10 15:46
@dingus-n we need some more time, please wait

**Comment by maxikuzmin** [comment] 2024-01-15 15:16
@dingus-n please try to switch the protocol from QUIC to HTTP/2, it will solve the problem.
Go to Settings -> General -> Advanced -> Low-level settings -> AdGuard VPN protocol 
I'm waiting for your feedback if this solved the problem

**Comment by dingus-n** [comment] 2024-01-15 16:10
@maxikuzmin Did it work for you? Because it didn't solve the problem for me. The first thing I did before writing this to you was change the protocols...

<details><summary>Screenshot 1:</summary>

![Screenshot_20240115_160534_Google Play Store.png](https://github.com/AdguardTeam/AdGuardVPNForAndroid/assets/74512154/edcf01f3-8157-43c2-8903-3209a170606d)


</details>

**Comment by maxikuzmin** [comment] 2024-01-15 16:19
@dingus-n you have QUIC selected in your logs, that's why I specified that. Do you have HTTP/2 protocol selected now?

**Comment by dingus-n** [comment] 2024-01-15 16:30
@maxikuzmin Yes, I have now selected the HTTP/2 protocol. This did not solve the problem. As i understand it, the problem is global and affects everyone? I dont understand why you would suggest a solution without testing it

**Comment by maxikuzmin** [comment] 2024-01-15 17:07
@dingus-n in my case there is no problem if I have HTTP/2 or even QUIC protocol selected.
But I think I realized what our difference is. In my case Integrated mode is set, because of that the problem does not recur for me. 
As a temporary solution you can choose Socks5 mode for now, that should help. We are looking into this problem

**Comment by dingus-n** [comment] 2024-01-15 17:15
@maxikuzmin Oh, thanks for the info about the integrated mode. I will try it in a few days and let you know

**Comment by maxikuzmin** [comment] 2024-01-22 18:13
@dingus-n any news?

**Comment by maxikuzmin** [comment] 2024-02-12 14:09
@dingus-n probably changing the addresses for the Mexico server fixed the issue. I am closing this issue for now. If the problem recurs in the future, please reopen the issue

**Closed by maxikuzmin** 2024-02-12 14:09 UTC
Labels: Bug, Priority: P4

**Comment by TPS** [comment] 2024-08-22 11:11
@maxikuzmin I've been having this issue with all v2.10n𝒙 when using the Chicago US server when using either Play or Aurora store, but using exception
- [ ] `gvt1.com`
- [x] `*.gvt1.com`

fixes it for me.  Is a refiled issue _really_ needed?
