### ISSUE TITLE
AdGuard VPN doesn't works on my device

### ISSUE THREAD

**Issue by Eno-Scott** [AdguardTeam/AdGuardVPNForAndroid#293] opened 2023-06-06 23:31 UTC
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.3.93

### Operating mode

Integration with AdGuard

### Environment

```markdown
- OS:Android 13
- Device:Samsung Galaxy A52s 5G
- Firmware:Build Version : TP1A.220624.014.A528BXXU3EWE1
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1.Log in fail
2.
3.

### Expected Behavior

When I try to log it say that is impossible to connect to the server for technical problems or because the VPN is blocked in my country...First it worked quite well in cooperation with A G Adblocker but I've already encountered that problem...I'm thinking to uninstall A G Adblocker and even A G VPN because I've already tried to uninstall and reinstall only the VPN (also tried the reinstall from a link sent by the assistance )...The only other option that I think could work is format the device..
Do you think that it depends on my ISP?

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

At now I'm using the Adguard VPN also on my Window 10 PC I've Nightly 2.1.903.0 there and it seems to works well..

**Comment by maxikuzmin** [comment] 2023-07-03 14:12
@Eno-Scott thanks for the long wait. How often do you see the dialog box about "impossible to connect to the server for technical problems or because the VPN is blocked in my country"? 
What country are you in?

**Comment by maxikuzmin** [comment] 2023-07-06 11:30
@Eno-Scott any news?

**Comment by Eno-Scott** [comment] 2023-07-10 06:55
@maxikuzmin any suggestion?

**Comment by maxikuzmin** [comment] 2023-07-12 14:11
@Eno-Scott please try collecting the logs [this way](https://adguard.com/kb/adguard-for-android/solving-problems/logcat/)
So we can see what's really going on.

**Comment by Eno-Scott** [comment] 2023-07-14 02:40
@maxikuzmin I've sent an email with the log file to support@adguard.com could you provide me a mail address of you or Adguard GitHub team or explain me the manner on how could I share it privately?
Because I never done it before and I don't know if the .zip file created has been saved somewhere on my phone,in that case I'd be able to attach it to the mail that I've received regarding your previous reply and send it to you!
I'm sorry for my annoyance but I'm a novice !
Thanks a lot for your help

**Comment by Eno-Scott** [comment] 2023-07-16 14:30
@maxikuzmin any suggestion ? I've tried to send the .zip file like a response to the mail that I've received from this chat but it is too big,I'll really need your help !

**Comment by maxikuzmin** [comment] 2023-07-31 21:23
@Eno-Scott I apologize for the long reply!
We have received your logs, it will take us some time.
In the future, you can send logs to devteam@adguard.com.
Normally, it would be easier to do this by uploading the logs in the app, but since you can't log into it, it required going through the instructions, but it looks like you did it, good for you! 
If we need anything else, I'll be sure to let you know!

**Comment by maxikuzmin** [comment] 2023-08-17 13:35
@Eno-Scott can you please clarify if you reproduced the problem when logging? It looks like you just collected logs without  logging into the VPN.
Please try to record logs after the problem is repeated

**Comment by maxikuzmin** [comment] 2023-08-22 15:42
@Eno-Scott any news?

**Comment by maxikuzmin** [comment] 2023-08-29 13:09
@Eno-Scott for the moment, I’m closing this issue. You can reopen the issue in the future if the problem persists

**Closed by maxikuzmin** 2023-08-29 13:09 UTC
Labels: Bug, Priority: P4

**Comment by Jmlevick** [comment] 2025-03-13 06:51
This also happens for me on all my iOS devices, (but not on Mac) even when they’re connected to the same network. I’ve already contacted support via email, but attaching my comment here as it is relevant. No solutions thus far.

Cc: @maxikuzmin
