### ISSUE TITLE
AdGuard VPN Nightly says license has expired & not connecting

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardVPNForAndroid#482] opened 2024-09-24 14:42 UTC
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.11 Nightly 2

### Operating mode

Integration with AdGuard

### Which DNS server do you use?

Custom DNS

### DNS protocol

DNS-over-QUIC

### Environment

```markdown
- OS: Android 14 One UI 6.1
- Device: Galaxy S24 Ultra
```

### Root access

- [ ] yes, I have it

### Issue Details

Steps to reproduce:
1. Update to AdGuard VPN Nightly for Android
2. Get a message saying licence has expired 
3. Try to connect to vpn server and I get kicked out

### Expected Behavior

Should work when trying to connect to VPN server.

### Actual Behavior

Get kicked out of app with connecting to VPN server and also saying my licence has expired.

### Screenshots

![Screenshot_20240923_165048_AdGuard VPN](https://github.com/user-attachments/assets/12259baf-a209-4d04-bb18-a58d4772c818)

**Comment by Batman2814** [comment] 2024-09-24 14:47
The logs have been sent.

**Comment by Versty** [comment] 2024-09-24 15:35
@Batman2814 We have received the log file. 
This bug should be fixed in the upcoming nightly version. Please let me know if the problem is no longer present on AdGuard VPN 2.11 nightly 3 when this version is out.

**Comment by Batman2814** [comment] 2024-09-25 01:14
Will do.

**Comment by pannal** [comment] 2024-09-25 20:56
Can confirm, I don't see any license issues, but the app closes immediately after connecting. Weirdly, this exclusively happens with German VPN endpoints.

**Comment by Versty** [comment] 2024-09-27 08:20
@pannal Sounds like a crash. Could you please keep enabled `Send anonymous crash reports` and reproduce the issue a few times in a row?

**Comment by Batman2814** [comment] 2024-09-27 12:12
Version 2.11 nightly build 3 works.

**Comment by Batman2814** [comment] 2024-09-27 13:36
I'm still receiving the message "Your license has expired," but I'm still able to connect. ![Screenshot_20240927_083340_One UI Home.jpg](https://github.com/user-attachments/assets/fd23e343-b453-4b6c-9538-7055a5d6edd9)

**Comment by pannal** [comment] 2024-09-27 16:26
> @pannal Sounds like a crash. Could you please keep enabled Send anonymous crash reports and reproduce the issue a few times in a row?

I've sent full system logs twice already. Do you still need crash reports?

**Comment by pannal** [comment] 2024-09-27 21:15
Issue resolved for me in Nightly 3

**Comment by Versty** [comment] 2024-10-04 09:46
@Batman2814 We have made an additional fix. This issue should be resolved completely in AdGuard VPN for Android 2.10 release. 

Please install and monitor a bit. Let me know if the problem is gone.

**Comment by Versty** [comment] 2024-10-04 09:52
@pannal Two system reports should be more than enough. 
Where did you send those files?

**Comment by pannal** [comment] 2024-10-04 11:33
@Versty as I've already told support, the issue has been fixed for me with Nightly 3

**Comment by Versty** [comment] 2024-10-07 11:09
@Batman2814 Does the problem still occur after updating to version 2.10?

**Closed as completed** 2024-10-11 08:53 UTC
Labels: Bug, Resolution: Fixed, Status: Closed, Priority: P4
