### ISSUE TITLE
Critical Kill Switch issues 

### ISSUE THREAD

**Issue by infinitewaveparticle** [AdguardTeam/AdGuardVPNForAndroid#173] opened 2022-04-26 22:01 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version - 2.0.166
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard VPN version:**
  -  2.0.166
- **VPN mode:**
  -  SOCKS5 / Compatibility Mode
- **Device:**
  -  Samsung Galaxy S7 Edge
- **Operating system and version:**
  -  Android 8.0
- **Root access:**
  -  No

### Expected Behavior

 After updating AdGuard VPN to the latest version I expected it to have the same or better functionality in all respects.

### Actual Behavior

 After installing the new version of AdGuard VPN it would not connect to any servers (just would say "Network unavailable" or something like that). I use either Compatibility Mode or the manual SOCKS5 mode because I want to use both AdGuard VPN and AdGuard ad-blocker. After several attempts to diagnose the issue myself I believe I figured out at least some of what is now happening:
When switching networks (e.g. from WiFi to mobile data) or even when reconnecting to a network (e.g. from Airplane Mode) AdGuard VPN no longer establishes a successful connection when the manual Kill Switch is enabled. The only way the user can get a successful connection is to:
1. Disable the "Block connections without VPN" system VPN setting for AdGuard;
2. Exclude the AdGuard VPN package from filtering (in Low Level Settings).
3. Open AdGuard VPN and connect to a server.
4. You can now switch the settings back again (enable the "Block connections without VPN" setting and remove the AdGuard VPN package from the list of excluded apps). The manual Kill Switch will now work as intended.

It's seriously extremely annoying that I now have to do that every time I switch networks or get disconnected from a network and reconnect. The only other option is to leave the manual Kill Switch disabled and exclude AdGuard VPN from filtering, but this is not what I want to do.

Likely unrelated, but another thing I noticed after updating AdGuard VPN is that one time the process was completely killed by battery optimization even though I have it disabled for the app (the permanent notification was removed from my notification bar). My phone is too old to use the Keep Alive process or whatever the new option is in settings because my battery already dies fairly quickly as it is.

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

 I have sent several emails about this issue to support over the past couple of days (including logs from the AdGuard VPN app). 597614 is the support request number. I hope this is enough information for you to fix this. Prior to the update I was using the latest 1.x version and never had this issue.

**Comment by maxikuzmin** [comment] 2022-04-27 07:55
@infinitewaveparticle we tried to reproduce your steps on a similar model of phone, the errors did not repeat. Could you please repeat the steps and send us the logs?

**Comment by infinitewaveparticle** [comment] 2022-04-27 13:02
I sent logs for AdGuard VPN already.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by maxikuzmin** [comment] 2022-04-29 10:24
@infinitewaveparticle  could you resend the logs according to the instructions you sent?
Please send a separate email to devteam@adguard.com

**Comment by maxikuzmin** [comment] 2022-05-04 07:59
@infinitewaveparticle ping

**Comment by infinitewaveparticle** [comment] 2022-05-04 16:35
Yes I will do that

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by infinitewaveparticle** [comment] 2022-05-04 16:38
Done... Sent 2 emails

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by maxikuzmin** [comment] 2022-05-13 07:00
@infinitewaveparticle such a task already exists. Issue at work. Duplicate off. 
If you know what steps led to the problem, or if you have additional comments, you can leave comments in this issue [#174](https://github.com/AdguardTeam/AdGuardVPNForAndroid/issues/174)

**Comment by infinitewaveparticle** [comment] 2022-05-15 00:25
No, these are NOT the same issues. I created BOTH of them so I should know. This one involves network connectivity not working after switching networks or enabling a network while Kill Switch is enabled (the SOCKS5 connection exists). #174 is entirely different - the network connectivity works, but the SOCKS5 connection is not created when using Compatibility Mode. It's a bit concerning to me that you thought these were the same issue.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by infinitewaveparticle** [comment] 2022-05-15 00:26
Plus I have already emailed and provided a TON of details and logs concerning this issue. It is 100% not the same issue as #174... #174 has nothing to do with the Kill Switch.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by infinitewaveparticle** [comment] 2022-05-15 00:32
You must reopen this issue. It is not fixed at all. One thing I will add is that when I switched from WiFi to mobile data today (with the manual Kill Switch fully enabled) I tried adding com.adguard.vpn to the QUIC exclusions (in AdGuard's Low Level Settings) and then switching AdGuard VPN's "protocol version" from HTTP/2 to QUIC; this worked temporarily, but seemed to be automatically switched back to HTTP/2 (like it says it will if "something goes wrong"). Once it switched back to HTTP/2 again it no longer worked (which is why this issue exists!).

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by maxikuzmin** [comment] 2022-05-16 08:20
@infinitewaveparticle yes, you are indeed right, we will put the issue back to work

**Comment by maxikuzmin** [comment] 2022-05-17 10:47
@infinitewaveparticle we have looked into your question. If you want to use both apps in Kill Switch mode, first of all, you need to configure Kill Switch in the system settings of the Adguard app, not in the Adguard VPN. You can also enable only "Always-on VPN". The "Block connections without VPN" function is not technically possible at the moment. This function is responsible for preventing you from accessing the internet without a VPN connection, and every time you switch networks, your internet connection source changes. This means that when you change the source of your internet connection, the VPN is immediately disabled, Adguard VPN cannot connect to the server because the system won't let you do so without a VPN connection, and therefore the entire internet is down. 
You can exclude Adguard VPN package from filtering in the settings of the lower level

**Comment by maxikuzmin** [comment] 2022-05-23 06:33
@infinitewaveparticle did you get it? Is the issue still relevant?

**Closed** 2022-05-25 08:37 UTC
Labels: Status: Closed, Resolution: Duplicate
