### ISSUE TITLE
Google Voice bypasses all VPN apps, including AdGuard VPN

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardVPNForAndroid#64] opened 2020-12-22 11:31 UTC
@EntropySmoke commented on [Tue Dec 22 2020](https://github.com/AdguardTeam/AdGuardVPNForWindows/issues/43)

### Prerequisites
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details
- **AdGuard VPN version:**
0.7.1
- **VPN mode:**
AdGuard VPN in VPN Mode, AdGuard AdBlocker in Local Proxy Auto-Mode
- **Operating system and version:**
Android 10 (rooted Lineage OS 17.1), no carrier/SIM card/data, WiFi/Bluetooth/USB-only connections
- **Other network-level software:**
AdGuard Home DNS server, AFWall+, custom IPTables scripts

### Expected Behavior
The expectation is that all apps would be tunneled through AdGuard VPN tunnel.

### Actual Behavior
TCP dumps show that Google Voice bypasses all VPN apps, including AdGuard VPN and OpenVPN Connect. Google Voice routes itself through Tun0 VPN adapter 99% of the time, but **per each received or made call** Google Voice always creates at least one direct connection over STUN UDP ports 19302-19305, which exposes both public and local IP. I can submit my TCPDump log, but privately. 

AdGuard AdBlocker in Local Proxy Auto-Mode log doesn't register that connection because Local Auto-Proxy Mode does not filter UDP packets. AdGuard AdBlocker's "Disable WebRTC" is enabled and works in almost all apps, but doesn't work for Google Voice...

AdGuard AdBlocker Filter Log detects Google Voice as "root" (instead of "Google Voice") when Google Voice makes a TCP connection to 216.239.36.145 over port 443 right before making and/or receiving a call. There are no other apps that register themselves as "root" in AdGuard Filter Log, but I don't know if this is important.

This behavior happens regardless of whether I use default IPTable rules/chain rules and/or AdGuard AdBlocker. 

### Additional Information
This affects all Android VPN apps, regardless of VPN protocol and regardless of DNS resolution settings, but AdGuard VPN could be the first one to make Google Voice calls be fully tunneled via VPN.

**Comment by artemiv4nov** [comment] 2022-05-18 16:54
Well, we investigated the issue deeply. We recommend to try to exclude the 1001 (or 1000) UID record from the "Excluded apps" in the Low-Level settings.
So far as the issue is old, I will close this issue. If it will relevant again, please re-open it.

**Closed** 2022-05-18 16:54 UTC
Labels: Bug, Resolution: Fixed, Status: Resolved, P3: Medium, Middle, Version: VPN v2.1
