### ISSUE TITLE
Chinese Simplified (zh-CN, China) is wrongly used for some servers names in Chinese Traditional (zh-TW, Taiwan) interface.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdGuardVPNForAndroid#3] opened 2020-06-26 06:00 UTC
Let servers' countries/cities names translated.
Please upload the strings of your servers' names to Crowdin.

**Comment by ameshkov** [comment] 2020-06-26 09:45
Why? Countries and cities have fixed names in every language

**Comment by lancelot-moon** [comment] 2020-06-26 09:51
Now, they’re English names.
But they’re also translated to Chinese Traditional by Ministry of Foreign Affairs.
We are used to read countries/cities’ Chinese names.

**Comment by ameshkov** [comment] 2020-06-26 09:56
Well, this might be a bug.

Look, here's how it works now: the backend server sends the list of locations + their names translated into the language that the app requests.

We should just figure out what went wrong -- either the app didn't request the proper language, or we haven't yet added City/Country names translations to the server.

Anyways, I don't think it makes sense to translate them via Crowdin, this can be done automatically perfectly well.

**Comment by lancelot-moon** [comment] 2020-06-26 10:04
I don’t know.
Maybe it’s because of no Chinese Traditional interface for app.
BTW, some countries/cities’ Chinese names are different between Taiwan and China.

**Comment by artemiv4nov** [comment] 2020-06-26 14:39
So, it is not a bug. We especially do not show translated cities and counties while the application doesn't contain translations for other languages.
Please, give us some time, translations will be available soon.

**Comment by lancelot-moon** [comment] 2020-07-16 15:41
zh-TW for AG VPN on Crowdin is done.
Please add zh-TW in the app.
I'll also check the Chinese Traditional translations of countries/cities.

**Comment by lancelot-moon** [comment] 2020-07-24 17:08
After adding zh-TW in the app, the names of country and city are English in the home page.

After entering the location page, they're Chinese Simplified.
Please fix it to Chinese Traditional since it's zh-TW interface.

**Comment by lancelot-moon** [comment] 2020-08-13 17:38
This isn't solved.
After adding zh-TW locale in AG VPN, some countries/cities’ names are wrongly shown with Chinese Simplified in zh-TW (Chinese Traditional).
Chinese Simplified is for zh-CN, Not for zh-TW.
You can upload countries/cities’ English names to Crowdin.
I'll translate.

**Comment by lancelot-moon** [comment] 2020-10-02 04:02
@artemiv4nov
Chinese Simplified is wrongly used for some servers names in zh-TW interface.
If you can't solve, please upload those servers names (countries/cities’ names) to Crowdin.

**Comment by lancelot-moon** [comment] 2020-10-02 08:11
Chinese Traditional cities names in zh-TW
Tokyo 東京
Seoul 首爾
Hong Kong 香港
Singapore 新加坡
Sydney 雪梨
Bangalore 班加羅爾
Johannesburg 約翰尼斯堡
Tel Aviv 特拉維夫
Istanbul 伊斯坦堡
Kiev 基輔
Warsaw 華沙
Luxemburg 盧森堡
Frankfurt 法蘭克福
Milan 米蘭
Paris 巴黎
Amsterdam 阿姆斯特丹
London 倫敦
Madrid 馬德里
São Paulo 聖保羅
Toronto 多倫多
Chicago 芝加哥
New York 紐約
New Jersey 紐澤西
Atlanta 亞特蘭大
Miami 邁阿密
Dallas 達拉斯
Seattle 西雅圖
Silicon Valley 矽谷
Los Angeles 洛杉磯

**Comment by ameshkov** [comment] 2020-10-02 08:55
@artemiv4nov 

Most likely this is a client-side bug, I see that these are properly translated on the server-side, but not in the app.

**Comment by artemiv4nov** [comment] 2020-10-02 12:37
This bug is already fixed in the developer app version.
@lancelot-moon , the alpha version will be available soon.

**Comment by lancelot-moon** [comment] 2020-10-29 14:21
No, this is still not fully fixed in v1.0 beta 12 (220).
Why do you not upload them to Crowdin for letting me manually fix them?

**Comment by lancelot-moon** [comment] 2020-10-29 19:30
Please fix these in your zh-TW.
You can copy correct translations from here https://github.com/AdguardTeam/AdGuardVPNForAndroid/issues/3#issuecomment-702591205
<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/QV2iSlY.jpg)

![image](https://i.imgur.com/gi9ZSzW.jpg)

![image](https://i.imgur.com/Kk9lDQ9.jpg)

![image](https://i.imgur.com/O1q6kH8.jpg)

![image](https://i.imgur.com/QDHEHSR.jpg)

![image](https://i.imgur.com/BXI9CV4.jpg)
</details><br/>

**Comment by ameshkov** [comment] 2020-11-01 19:36
Fixed it

**Comment by lancelot-moon** [comment] 2020-11-02 09:04
Checked.
Andrey had fixed all.
Thanks, you can close this.

**Closed** 2020-11-02 09:07 UTC
Labels: Resolution: Fixed, Status: Resolved
