### ISSUE TITLE
VPN doesn't reconnect after network chage

### ISSUE THREAD

**Issue by RicoZico99** [AdguardTeam/AdGuardVPNForAndroid#180] opened 2022-05-18 04:25 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [yes ] I am running the latest version
- [ yes] I checked the documentation and found no answer
- [ yes] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard VPN version:**
  - 
- **VPN mode:**
  - 
- **Device:**
  - 
- **Operating system and version:**
  - 
- **Root access:**
  - 

### Expected Behavior

I expect the VPN to be able to reconnect instantly when I walk out the door and my phone switches from my home wifi to the cellular network

### Actual Behavior

Adguard VPN is not able to reconnect after the network change between cellular to wifi or even between two wifi networks, it just get stuck on trying to connect Waiting for connection. 
I have the same exact issue on two different phones different models.
I have this issue since October 2021. I have sent emails and requests but never got the help to fix the issue.

### Screenshots

<details><summary>:</summary>

![Uploading Screenshot_2022-05-17-23-20-25-27_40deb401b9ffe8e1df2f1cc5ba480b12.jpg…]()

</details>

### Additional Information

![Uploading Screenshot_2022-05-17-23-20-25-27_40deb401b9ffe8e1df2f1cc5ba480b12.jpg…]()

**Comment by RicoZico99** [comment] 2022-05-18 04:30
- **AdGuard VPN version:**
  - v2.1 beta 1, 25 
- **VPN mode:**
  - Adguard compatible mode
- **Device:**
  - OnePlus 8 Pro
- **Operating system and version:**
  -  Android 11 & 12
- **Root access:**
  - No

**Comment by maxikuzmin** [comment] 2022-05-18 08:18
@RicoZico99 uploaded screenshots do not open. 
I don't have this error repeated.
Could you please reattach the proof? Or maybe a link to a video of the problem repeating.

To troubleshoot this issue, we need to get the app logs.

Here's what we need you to do:

1. Open AdGuard VPN app settings;
2. Advanced settings --> Logging level --> Extended;
3. Reproduce the issue and remember the exact time it happened;
4. Open Support --> Export logs and system info;
5. Send the archive to devteam@adguard.com and mention this issue number in the subject.

**Comment by maxikuzmin** [comment] 2022-05-23 06:36
@RicoZico99 did you send the logs and proofs?

**Comment by Birbber** [comment] 2022-05-30 13:56
Closing this issue due to no reply.

**Closed** 2022-05-30 13:56 UTC
Labels: Waiting for data
