### ISSUE TITLE
Every time I open app keyboard appears

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdGuardVPNForAndroid#373] opened 2023-10-18 13:31 UTC
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.5.26

### Operating mode

None

### Environment

```markdown
- OS: Android 8.1
- Device: Xiaomi Mi Pad 4
- Firmware: N/A
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:

1. Use the search and connect to the desired location
2. Minimize your keyboard
3. Minimize apps by going to the home screen
4. Reopen AdGuard VPN

### Expected Behavior

Every time I open an app, the main screen with the connection status is displayed, without the keyboard appearing.

### Screenshots

<details><summary>Screenshot 1:</summary>

![Screenshot_2023-10-10-19-30-04-363_com adguard vpn](https://github.com/AdguardTeam/AdGuardVPNForAndroid/assets/19418601/7cb5905f-42bc-417c-841a-afb32b8fd73c)

</details>

### Additional Information

[app_info.txt](https://github.com/AdguardTeam/AdGuardVPNForAndroid/files/13026269/app_info.txt)
[logs.zip](https://github.com/AdguardTeam/AdGuardVPNForAndroid/files/13026273/logs.zip)

**Comment by Versty** [comment] 2023-10-19 14:48
@rakleed Hi! 
If you reinstall the application, does the issue persist?

**Comment by Versty** [comment] 2023-10-19 14:59
@rakleed Please uninstall the application, and install it again. 
Would the problem persist after re-installation?

**Comment by rakleed** [comment] 2023-10-19 15:05
@Versty how will this help if the problem appeared immediately after installing the application?

**Comment by Versty** [comment] 2023-10-19 15:12
@rakleed This can be a rare installation error causing the keyboard to open unintentionally.
So the problem appeared and then reappeared after reinstallation?

**Comment by Versty** [comment] 2023-10-23 08:50
@rakleed Any news?

**Comment by rakleed** [comment] 2023-10-25 20:28
@Versty it did not help.

**Comment by Versty** [comment] 2023-10-26 15:43
@rakleed 
Let's see what exactly is wrong with your device. Please collect debug logs for further investigation by following the steps below. 

1. Enable debug logging:
 *Settings -> General -> Advanced settings -> Logging level -> Extreme*

2. Reproduce the issue and remember the exact time when it happened

3. Collect logs:
  *Settings -> General -> Advanced settings -> Export logs and system info*

4. Send this file to [devteam@adguard.com](mailto:devteam@adguard.com):
    - mention the `373` number in the subject
    - specify the exact time when the issue occurred

**Comment by rakleed** [comment] 2023-11-01 20:26
@Versty done

**Comment by Versty** [comment] 2023-11-02 09:14
@rakleed Thank you! 
The logs have been received and will be examined by the developers. 
We will let you know the results.

**Comment by Versty** [comment] 2023-12-11 07:10
@rakleed Hi! 

Does the issue persist on AdGuard VPN for Android version 2.6 as well?

**Comment by rakleed** [comment] 2023-12-12 19:40
@Versty yes.

**Comment by Versty** [comment] 2024-02-02 08:55
@rakleed Hi! 
The developers finished reviewing your logs. And they'd like to know where the text appears when you type something on the keyboard after the keyboard automatically appears. 
Could you please try it and provide the information?

**Comment by rakleed** [comment] 2024-02-05 19:03
@Versty Location search field.

**Comment by Versty** [comment] 2024-03-07 08:49
@rakleed We have found a way to reproduce this bug on your side. 
Will be fixed!

**Comment by Versty** [comment] 2024-05-20 15:59
@rakleed Please test if the issue is gone with AdGuard VPN for Android version 2.8.1, and let me know results.

**Closed** 2024-05-21 07:49 UTC
Labels: Bug, Junior, Priority: P4, Version: VPN v2.8

**Comment by rakleed** [comment] 2024-06-09 18:18
@Versty it works now correctly, thanks.
