### ISSUE TITLE
Adguard VPN not working on google tv

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardVPNForAndroid#255] opened 2023-02-06 18:24 UTC
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [ ] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.2 3

### Operating mode

VPN

### Environment

```markdown
- OS:Android 12 OS
- Device:Google TV streaming stick
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1.
2.
3.

### Expected Behavior

When I have adgaurd vpn on a US state I'm not getting US Netflix. I was but then it suddenly kicked me out. 

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Batman2814** [comment] 2023-02-15 18:46
When I have Adgaurd VPN for android on my google tv streaming stick which was set to a USA state New York and I wasn't getting US Netflix and this is not the first time it has done this. I've got us netflix with Adgaurd VPN on my google tv streaming stick. so there is definitely a problem.

**Comment by maxikuzmin** [comment] 2023-02-28 11:30
@Batman2814 sorry for the long reply. What version of Netflix are you using? Is it repeated with other locations?

**Comment by Batman2814** [comment] 2023-02-28 15:06
The current Netflix version on google tv 4k streaming stick is version 10.0.3 which was updated on February 21, 2023. Also tried to connect to multiple US servers and wouldn't give me U.S  Netflix.

**Comment by maxikuzmin** [comment] 2023-03-03 14:49
@Batman2814 I haven't had this problem yet. Is it repeated with all 11 U.S. locations? Please check in the Android TV browser at https://adguard.com/en/test.html if the location is displayed as selected?
Also, please clarify, with other locations it is repeated?

**Comment by Batman2814** [comment] 2023-03-03 18:05
I have Adguard VPN connected to New York this was on the stable version so I installed the Nighly version of Adguard VPN for android and same problem. I went into the tv browser with the URL you told me to it is checked as Running on the Adguard VPN server in the United States, New York but for some reason, it is not showing U.S. Netflix.
Aso was on:
Denver, United States
Chicago, United States
New York, United States
Atlanta, United States
there is probably more US States but not going to check all of them.
This only happens on the Netflix App of Google's TV 4K Streaming Stick. Works fine on the Disney Plus app and Amazon Prime Video app where it gives me US Prime and Disney. Just not for Netflix. 
At times yes sometimes it will give me US Netflix but most of the time it stays on Canadian Netflix. 

I'm able to get US Netflix when using Surfshark VPN but for some reason, Adguard VPN for Android is not Working to get US Netflix.

So I hope this is enough information for you guys to fix.

**Comment by maxikuzmin** [comment] 2023-03-07 17:57
@Batman2814 okay. Try to check on other American locations for now, maybe that will help as a temporary solution

**Comment by Batman2814** [comment] 2023-03-07 18:00
I've done that to all US locations you have and it seems to not work at random times.

**Comment by maxikuzmin** [comment] 2023-03-20 19:02
@Batman2814 we have tested the Chromecast With Google TV - 4k device, we still do not have this problem repeated.
Have you tried reinstalling the application? Also, when you connect to a location, what country is listed in the Member tab? It would also be a good idea to connect to the location and see what IP is listed in the Network tab of the Netflix app.

**Comment by maxikuzmin** [comment] 2023-03-22 16:26
@Batman2814 any news?

**Comment by Batman2814** [comment] 2023-03-22 18:28
I just saw there was an update available for Adguard VPN Nighly for Android on my google tv so I'm going to test that version out to see if there are any problems with the Netflix app to see if I can still get US Netflix because the problem was it was only sometimes able to connect to US Netflix so let you know if it is not able to stay on US Netflix while Adguard VPN is on a U.S server. So could you give me about a week to see if it connects to it every time and I'll let you know in that week or after the week is over from today if that's ok with you? I would like to be sure if the problem is still here.

**Comment by Batman2814** [comment] 2023-04-03 18:48
Need more time to test it out. Should be able to let you know this month. Just been busy but I will test it out when I'm not busy at times of the day.

**Comment by Batman2814** [comment] 2023-04-04 14:53
So far, when I used Adguard VPN on my Google TV 4k streaming stick on a U.S. server, I am able to use U.S Netflix. Let me test it out until the end of the week because I'll be watching US Netflix a lot this week so if I have no problems I will close this issue myself at the end of the week.

**Comment by Batman2814** [comment] 2023-04-09 19:06
So far when using the Adguard VPN Nightly version on my Google TV 4K Streaming Stick Netflix has been staying connected to the U.S. State server.
So I'm going to close this issue report.

**Comment by maxikuzmin** [comment] 2023-04-12 13:56
@Batman2814 when you connect to a location, what country is listed in the Member tab? It would also be a good idea to connect to the location and see what IP is listed in the Network tab of the Netflix app.
Does this problem show up right away when you sign in to Netflix? Please describe the exact steps and error in the Netflix app

**Comment by Batman2814** [comment] 2023-04-16 18:51
I connected to Atlanta in Adguard VPN on my Google TV. the IP address listed is 172.20.2.13 in Network Tab.
Like I said before it happens at random times when I can't get US Netflix. One of the reasons I can tell I'm not getting US Netflix is because the show that I want is NCIS which is only available on US Netflix. Also under Member where it shows the country is under which says the US but I'm not getting US Netflix it's staying on Canadian Netflix. For me to finally get US Netflix to wait and just come back to it at a later date. I don't have this problem with Surfshark VPN so the problem is with Adguard VPN.

**Comment by maxikuzmin** [comment] 2023-04-17 16:43
@Batman2814  these are local settings, they do not fit. Please connect to the location, repeat the problem and use your browser in android tv to go to the website https://adguard.com/whoami.txt
Then we can see if you have the right connection and we can evaluate it

**Comment by Batman2814** [comment] 2023-04-17 17:03
I'll have to wait until it happens again but when it does I'll put the results here.

**Comment by maxikuzmin** [comment] 2023-04-26 17:23
@Batman2814 any news?

**Comment by Batman2814** [comment] 2023-04-26 17:37
Need more time to test it out on the new Adguard VPN for the Android Nightly update and also to see if the issue is reproduced on this version so I can paste the link you sent me into the browser on my Google TV Streaming Stick.

**Comment by Batman2814** [comment] 2023-04-27 01:10
So I was able to catch the Netflix app doing it again being not showing US Netflix even though Adgaurd VPN is on us server. Here's a picture of what I put in the browser on the Google TV Stick.

![20230426_200733](https://user-images.githubusercontent.com/96619913/234734369-7fae8b1c-a276-4047-a968-c1a44dee68a2.jpg)

**Comment by maxikuzmin** [comment] 2023-05-12 10:42
@Batman2814 thanks, I tested with this IP, and I couldn't even get into the Netflix app, not even into the website. But the next day I successfully logged into Netflix under the same IP.
Looks like IP blocking, but it's temporary for some reason. Maybe it depends on Netflix, which entry point is connected to when trying to log in to Netflix.
We have now replaced IP 155.138.222.6 with another one. Please observe the behavior and see if this problem repeats now.

**Comment by Batman2814** [comment] 2023-05-12 21:16
The problem is still happening. Here's another test I took.
![20230512_161345](https://github.com/AdguardTeam/AdGuardVPNForAndroid/assets/96619913/5c88bc0a-c617-4dcc-8003-ea85ed340bf7)

**Comment by maxikuzmin** [comment] 2023-06-01 16:19
@Batman2814 globally, traffic in streaming services goes through special proxies that redirect traffic to millions of other IPs. That means the probability that you will connect to the same IP is small.
I tried to reproduce your problem using AdGuard VPN + Netflix, and so far I haven't been able to reproduce it.
You may sometimes be directed to a bad IP. I would recommend trying to reconnect to the location or reopen the app, this should help to switch to a different IP

**Comment by maxikuzmin** [comment] 2023-06-22 12:54
@Batman2814 I have never been able to reproduce this. I hope reconnecting to the location or reopening the app helped you, right now that's the only way to fix the problem. For the moment, I’m closing this issue

**Closed by maxikuzmin** 2023-06-22 12:54 UTC

**Comment by Batman2814** [comment] 2023-09-19 19:10
Can you reopen this issue? Sent logs where I wasn't able to get US Neflix on US servers at all. Everything is explained in email with the logs.
