### ISSUE TITLE
Cannot open local address when VPN is enabled

### ISSUE THREAD

**Issue by depler** [AdguardTeam/AdGuardVPNForAndroid#90] opened 2021-05-05 12:48 UTC
Have following error in Google Chrome when trying to open my router admin panel. The subnet 192.168.0.0/16 is added to exclusion list in AdGuard VPN by default, but that is not woking.

![Screenshot_2021-05-05-15-45-03-870_com android chrome](https://user-images.githubusercontent.com/13541699/117143042-0fc42580-adb9-11eb-8cab-7f2e3d8b8263.jpg)

**Comment by ameshkov** [comment] 2021-05-07 07:11
> wireguard VPN by default

In AdGuard VPN you mean?

@artemiv4nov how could this be?

**Comment by depler** [comment] 2021-05-07 08:30
Probably with VPN enabled the request is sent with different source IP (which is VPN network address) and router allow only local network connections (which is 192.168.1.0/24 subnet)

**Comment by artemiv4nov** [comment] 2021-05-11 07:28
@depler Hello!
Your screenshot looks like it shot on iPhone. Are you sure you choose the right repo?

**Comment by artemiv4nov** [comment] 2021-05-11 09:38
Hmm, try to add this exclusion to the low-level setting, which called "IPv4 ranges excluded from VPN"

**Comment by depler** [comment] 2021-05-11 10:37
> Hmm, try to add this exclusion to the low-level setting, which called "IPv4 ranges excluded from VPN"

I did this exactly many times with different IPs and subnets - there is no difference. As I wrote before, my Keenetic Lite router is denying connection to admin panel when AdGuard VPN is enabled. There are no such problems when I connect to other devices in same subnet. I don't know why.

**Comment by depler** [comment] 2021-05-11 11:25
Done

**Comment by Chinaski1** [comment] 2021-05-17 12:20
@depler 

Could you please record one more log archive using AdGuard VPN in VPN mode (Without the main AdGuard app)?

**Comment by admitrevskiy** [comment] 2021-05-19 10:50
@depler Hi!

You are trying to use AdGuard and AdGuard VPN in compatibility mode, as I can see in the logs you've sent. In this case you should manage excluded routes in AdGuard: Advanced -> Low Level Settings -> pref.ipv4.routes.excluded

What was going on? Android's VPN service is managed on AdGuard side in compatibility mode, AdGuard VPN only forwarding requests throw selected location. 

Furthermore, please don't trim logs: there is a lot of useful information on the startup.

**Comment by admitrevskiy** [comment] 2021-05-28 10:49
@depler hi! 
Are there any updates on this issue? Please, let me know if the problem is gone or send us logs if it is not.

**Comment by depler** [comment] 2021-05-28 17:51
The problem is still persist, despite excluded IP range 192.168.0.0/16 both in AdGuard VPN and AdGuard (default settings). Sorry, don't really have time to dig further with logs right now. I can only say, that any other local http address in my network working just fine - it is only keenetic lite router blocking connections by some reason. No big deal anyway, feel free to close my comment.

**Comment by admitrevskiy** [comment] 2021-06-09 14:02
This case is critical for the proper functioning of applications and is not repeated on our side.
Unfortunately, I can't close this issue with a clear conscience until I'm sure there are no problems on the application side.

@depler you will help us a lot if you send us trace logs from both applications with the exact time of the problem occurrence.

**Comment by artemiv4nov** [comment] 2021-07-02 17:03
Closed since not reproducable.

**Closed by artemiv4nov** 2021-07-02 17:03 UTC
Labels: Status: In Progress, Version: VPN v2.0
